### ISSUE TITLE
Map parsing issue?

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#160]
There are a lot of maps in the `dev` env that appear to not be parsing all strings. One example is `1cor1.ar.cf.svg`. Please investigate to determine why.

![Screenshot 2023-08-31 at 4 33 07 PM](https://github.com/etenlab/crowd.rocks/assets/1165460/d1c5c26f-8915-4d5d-b34a-04a5ff71ae1e)

**Comment by ForeverYoung1208** [comment]
I wasn't able to reproduce due to database cleanup, but i have an assumption that it was newly loaded map, and no any words were translated after the map was loaded, so translation routines wasn't triggered.
So i've added automatic transalation of newly loaded map to all languages which have at least one translated word from original map translated to.
PR
https://github.com/etenlab/crowd.rocks/pull/166

**Comment by michaelmarshall** [comment]
It looks like that was it. Thanks Ihor.
