### ISSUE TITLE
Map parser update

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#233]
I'm not sure why the parser isn't picking up the text in this map: https://crowd.rocks/US/en/1/maps/details-translated/233

There are single `tspan` nodes inside of `text` nodes.

Please update the parser to work for this map.

**Comment by ForeverYoung1208** [comment]
Somehow the data about this map (translated_map_id: 233) doesn't exist in the DB, or corrupted. Maybe the map was deleted.
I can't see the dev DB so i can't tell more...  But definetely, error message should be shown to the user, so i'll improve feedback in case of error.

So it is not isssue of the map parser. At least it isn't directly related to map parser (because i can't tell now why this translated map doesn't exist/corrupted)

**Comment by michaelmarshall** [comment]
ok sounds good. I just checked the dev site version of the map and it looks good. it might have been deleted in prod and replaced.
