### ISSUE TITLE
Smartcat bot

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#288]
[Smartcat API](https://developers.smartcat.com/getting-started/#smartcat-cli)

I'm not sure what all Smartcat can do, but try to see if we can get the same functionality as Google Translate. We also need to be able to send strings to Smartcat so users can use the Smartcat UI if they want to.

**Comment by ForeverYoung1208** [comment]
Among other smartcat's services i've found their so called 'smartTranslation' service. It looks like it can provide us with just translation ' arbitraty string to string' which is suitable for us.
https://developers.smartcat.com/api/#smartcat-api-smarttranslation
but to get it and try it, I need username and APIkey for authorization.  

Those can be generated only under administrator's account:
https://developers.smartcat.com/api-guides/#when-to-use-smartcat-api
So...  i need either administrator account or generated credentials.

**Comment by ForeverYoung1208** [comment]
When i try to make a POST request to smartcat's API, I'm getting responce 
``` 
Error processing request. Correlation id: 657807d7-1632-43cf-a911-25b566a34046, Trace id: 4c7db4ab5c8370c7cf645b5a19d2f89e
Incorrect profile `crowd_rocks_profile`
```
Despite i've  already created smart translation profile `crowd_rocks_profile`.

I sent an email to their support, got the next answer:
`Hi Ihor, 
Just shared the issue you're running into with our support team and they should be in touch soon. `

Blocked until support responce.

**Comment by ForeverYoung1208** [comment]
I got the next answer:
You need to specify the ID of the profile instead of its name. You can get the ID from the address bar like this:
![Image](https://github.com/etenlab/crowd.rocks/assets/767556/1aaa4ce6-1f92-4541-9afd-92f8296ff6aa)

...
I used this information, and it worked. But now i have another problem:

HTTP/1.1 402 Payment Required

{ "message": "Not enough Smartwords" }

despite i never used any Smartwords, and it shows my balance as 15000.

So, still blocked, still in touch with support.
