### ISSUE TITLE
Bug: Backend terminated due to DB connection issue.

### ISSUE THREAD

**Issue by lucky-gru** [etenlab/crowd.rocks#436]
Connect your backend to 'dev db'.

1. Go to the ai bot tool and select English as the source language and Dutch/Flemish as the target language.

2. Click the translate button.

3. When I go to the map list page and switch languages several times, the backend server terminates with an error.

![Image](https://github.com/etenlab/crowd.rocks/assets/42648696/8733fe9a-2587-4b63-a18e-d0f9b8843d48)

**Comment by ForeverYoung1208** [comment]
Tried for several times, but can not repeat.
Yet i've checked  `mapsService.getAllMapsList` method (it is called when you go to the map list page and switch languages ) , it is wrapped into try...catch statement.
So if this bug still persist, we need more details how to repeat it in order to be able to investigate it.
